# Generated by Django 4.1.4 on 2022-12-09 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_title_product_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='address',
        ),
    ]
