# Generated by Django 4.1.4 on 2022-12-11 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.CreateModel(
            name='Subproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subproduct_title', models.CharField(max_length=200)),
                ('subproduct_image', models.ImageField(upload_to='')),
                ('subproduct_product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='store.product', verbose_name='Product')),
            ],
            options={
                'verbose_name_plural': 'Subproducts',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_addons', models.CharField(blank=True, max_length=200)),
                ('product_description', models.TextField()),
                ('product_slug', models.SlugField(default=1, max_length=200)),
                ('product_available', models.BooleanField(default=True)),
                ('product_subcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='store.product', verbose_name='Subproducts')),
            ],
            options={
                'verbose_name_plural': 'store',
            },
        ),
    ]
