# Generated by Django 4.1.4 on 2022-12-13 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_product_options_alter_product_image_subproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproduct',
            name='subproduct_product',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'store'},
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.DeleteModel(
            name='Subproduct',
        ),
    ]
